language: groovy

sudo: required

matrix:
  include:
    - jdk: oraclejdk8
    - jdk: openjdk7
    - jdk: openjdk6

addons:
  apt:
    packages:
      - openjdk-6-jdk

# use bouncycastle security provider to avoid:
# javax.net.ssl.SSLException: ... java.security.InvalidKeyException: EC parameters error
before_install:
  - |
    echo ${JAVA_HOME}
    if [ $TRAVIS_JDK_VERSION == "openjdk7" ]; then
      JAVA_ETC=java-7-openjdk
    elif [ $TRAVIS_JDK_VERSION == "openjdk6" ]; then
      JAVA_ETC=java-6-openjdk
    fi
    if [ $TRAVIS_JDK_VERSION == "openjdk6" ] || [ $TRAVIS_JDK_VERSION == "openjdk7" ]; then
      BCPROV_FILENAME=bcprov-ext-jdk15on-158.jar
      wget "https://bouncycastle.org/download/${BCPROV_FILENAME}"
      sudo mv $BCPROV_FILENAME ${JAVA_HOME}/jre/lib/ext
      sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/${JAVA_ETC}/security/java.security
      echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/${JAVA_ETC}/security/java.security
    fi

#      JAVA7_HOME=`echo ${JAVA_HOME} | sed -e s/java-6/java-7/`
#      sudo ln -s ${JAVA_HOME}/jre/lib/security/cacerts ${JAVA_HOME}/jre/lib/security/jssecacerts
#      ls -l ${JAVA_HOME}/jre/lib/security/
#      ls -l ${JAVA7_HOME}/jre/lib/security/
#      ls -l /etc/ssl/certs/java
#      sudo mv ${JAVA_HOME}/jre/lib/security/cacerts ${JAVA_HOME}/jre/lib/security/cacerts.orig
#      sudo cp jssecacerts ${JAVA_HOME}/jre/lib/security/cacerts
#      sudo mv ${JAVA_HOME}/jre/lib/security/cacerts ${JAVA_HOME}/jre/lib/security/cacerts.orig
#      echo | openssl s_client -showcerts -connect services.gradle.org:443 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/gradle.crt
#      sudo ${JAVA_HOME}/bin/keytool -import -alias gradle.org -noprompt -trustcacerts -storepass changeit -keystore ${JAVA_HOME}/jre/lib/security/cacerts -file /tmp/gradle.crt
#      sudo ${JAVA_HOME}/bin/keytool -import -alias gradle.org -noprompt -trustcacerts -storepass changeit -keystore ${JAVA_HOME}/jre/lib/security/jssecacerts -file /tmp/gradle.crt
#      keytool -list -storepass changeit -keystore ${JAVA_HOME}/jre/lib/security/cacerts
#      sudo mv ${JAVA_HOME}/jre/lib/security/jssecacerts ${JAVA_HOME}/jre/lib/security/jssecacerts.orig
#      sudo cp ${JAVA7_HOME}/jre/lib/security/jssecacerts ${JAVA_HOME}/jre/lib/security/jssecacerts

install: true

before_script:
  - |
    if [ $TRAVIS_JDK_VERSION == "openjdk6" ] || [ $TRAVIS_JDK_VERSION == "openjdk7" ]; then
      export _JAVA_OPTIONS=-Xms1024m\ -Xmx2048m
      if [ $TRAVIS_JDK_VERSION == "openjdk6" ]; then
        jdk_switcher use oraclejdk8
        ./gradlew assemble
        jdk_switcher use openjdk6
      fi
    else
      unset _JAVA_OPTIONS
    fi

script: ./gradlew clean test

# As recommended in:
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
