language: groovy

sudo: required

matrix:
  include:
    - jdk: openjdk6
    - jdk: oraclejdk8

addons:
  apt:
    packages:
      - openjdk-6-jdk

dist: trusty

# use bouncycastle security provider to avoid:
# javax.net.ssl.SSLException: ... java.security.InvalidKeyException: EC parameters error
before_install:
  - |
    echo ${JAVA_HOME}
    if [ $TRAVIS_JDK_VERSION == "openjdk7" ]; then
      JAVA_ETC=java-7-openjdk
    elif [ $TRAVIS_JDK_VERSION == "openjdk6" ]; then
      JAVA_ETC=java-6-openjdk
      JAVA7_HOME=`echo ${JAVA_HOME} | sed -e s/6/7/g`
      echo ${JAVA7_HOME}
      sudo mv ${JAVA_HOME}/jre/lib/security/cacerts ${JAVA_HOME}/jre/lib/security/cacerts.orig
      sudo cp ${JAVA7_HOME}/jre/lib/security/cacerts ${JAVA_HOME}/jre/lib/security/cacerts
      sudo mv ${JAVA_HOME}/jre/lib/security/jssecacerts ${JAVA_HOME}/jre/lib/security/jssecacerts.orig
      sudo cp ${JAVA7_HOME}/jre/lib/security/jssecacerts ${JAVA_HOME}/jre/lib/security/jssecacerts
    fi
    if [ $TRAVIS_JDK_VERSION == "openjdk6" ] || [ $TRAVIS_JDK_VERSION == "openjdk6" ]; then
      BCPROV_FILENAME=bcprov-ext-jdk15on-158.jar
      wget "https://bouncycastle.org/download/${BCPROV_FILENAME}"
      sudo mv $BCPROV_FILENAME ${JAVA_HOME}/jre/lib/ext
      sudo perl -pi.bak -e 's/^(security\.provider\.)([0-9]+)/$1.($2+1)/ge' /etc/${JAVA_ETC}/security/java.security
      echo "security.provider.1=org.bouncycastle.jce.provider.BouncyCastleProvider" | sudo tee -a /etc/${JAVA_ETC}/security/java.security
    fi

#      echo | openssl s_client -showcerts -connect services.gradle.org:443 2>&1 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' > /tmp/gradle.crt
#      sudo ${JAVA_HOME}/bin/keytool -import -alias gradle.org -noprompt -trustcacerts -storepass changeit -keystore ${JAVA_HOME}/jre/lib/security/cacerts -file /tmp/gradle.crt
#      sudo ${JAVA_HOME}/bin/keytool -import -alias gradle.org -noprompt -trustcacerts -storepass changeit -keystore ${JAVA_HOME}/jre/lib/security/jssecacerts -file /tmp/gradle.crt
#      keytool -list -storepass changeit -keystore ${JAVA_HOME}/jre/lib/security/cacerts

install: true

#before_script:
#  - |
#    if [ $TRAVIS_JDK_VERSION -eq "openjdk6" ] || [ $TRAVIS_JDK_VERSION -eq "openjdk6" ]; then
#      export _JAVA_OPTIONS=-Xms1024m\ -Xmx2048m
#    else
#      unset _JAVA_OPTIONS
#    fi

script: travis_wait 60 ./gradlew test

# As recommended in:
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
